version: '3' 

services:
  jupyter:
    image: jupyter/datascience-notebook 
    command: ["start-notebook.sh", "--NotebookApp.token=''"]
    volumes:
      - "${DATA:-./data}:/home/jovyan/work" 
      - "${PASSWORD:-./jupyter_notebook_config.json}:/home/jovyan/.jupyter/jupyter_notebook_config.json" 
    ports:
      - "${WEB:-9988}:8888"
